# Generated by Django 3.1 on 2021-05-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0002_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_type', models.CharField(max_length=15)),
                ('act_time', models.DateTimeField(auto_now_add=True)),
                ('act_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='msf_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=15)),
                ('console_id', models.CharField(max_length=20)),
                ('session_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
