# Generated by Django 3.1 on 2021-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='token',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
