# Generated by Django 3.1 on 2021-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0005_online_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='console_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('prompt', models.CharField(max_length=50)),
                ('console_id', models.CharField(max_length=20)),
                ('session_id', models.CharField(max_length=20)),
            ],
        ),
    ]
