# Generated by Django 3.1 on 2021-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0008_auto_20210508_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='msf_status',
            name='andom',
            field=models.CharField(default='xxx', max_length=50),
        ),
    ]
