# Generated by Django 3.2 on 2021-05-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0009_msf_status_andom'),
    ]

    operations = [
        migrations.CreateModel(
            name='exploit_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploit_name', models.CharField(max_length=50, null=True)),
                ('exploit_mod', models.CharField(max_length=50, null=True)),
                ('exploit_rhost', models.CharField(max_length=20, null=True)),
                ('exploit_payload_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='msf_status',
            old_name='andom',
            new_name='random_num',
        ),
        migrations.AlterField(
            model_name='act_info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='console_status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='msf_status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='online',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
