# Generated by Django 3.2 on 2021-05-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0012_auto_20210508_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=20)),
                ('session_type', models.CharField(max_length=20)),
                ('session_host', models.CharField(max_length=20, null=True)),
                ('tunnel_local', models.CharField(max_length=20, null=True)),
                ('tunnel_peer', models.CharField(max_length=20, null=True)),
                ('session_uname', models.CharField(max_length=20, null=True)),
                ('session_info', models.CharField(max_length=200, null=True)),
                ('session_via_exp', models.CharField(max_length=50, null=True)),
                ('session_via_pay', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='console_status',
            name='remark',
            field=models.CharField(default='console', max_length=20),
        ),
        migrations.AddField(
            model_name='login',
            name='login_ip',
            field=models.CharField(default='127.0.0.1', max_length=15),
        ),
    ]
